### ISSUE TITLE
statusesUpdate() fails to post status because endpoint doesn't support json

### ISSUE THREAD

**Issue by bwegrzyn** [zendframework/ZendService_Twitter#48]
The statusesUpdate() method that is used to post a new status takes all parameters (including status), json_encodes them, and adds them to the body of the request. It then makes a POST request with Content-Type set to application/json.

Unfortunately, it appears that the `/1.1/statuses/update.json` endpoint does not support this. It requires the `status` text to be passed as a parameter on the url as such `/1.1/statuses/update.json?status=test`.

This means that the statusesUpdate() method fails to post a status with the response being:

```json
{"errors":[{"code":170,"message":"Missing required parameter: status."}]}
```

Looks like this "bug" was introduced in #41.

### Code to reproduce the issue

```php
$client->statusesUpdate('test status');
```

### Expected results
JSON of the tweet that was posted.

### Actual results
```json
{"errors":[{"code":170,"message":"Missing required parameter: status."}]}
```

This can be verified using the Twurl tool:

```bash
$ twurl --header "Content-Type: application/json" -X POST -d '{"status": "test status"}' /1.1/statuses/update.json
{"errors":[{"code":170,"message":"Missing required parameter: status."}]}

$ twurl -X POST -d 'status=test status' /1.1/statuses/update.json
{"created_at":"Sat Oct 28 07:32:08 +0000 2017","id":924176943666290689,...}

$ twurl --header "Content-Type: application/json" -X POST "/1.1/statuses/update.json?status=test"
{"created_at":"Sat Oct 28 07:32:52 +0000 2017","id":924177129331351552,...}
```

**Comment by BnitoBzh** [comment]
pull request [#49](https://github.com/zendframework/ZendService_Twitter/pull/49)

**Comment by weierophinney** [comment]
I've verified this locally. However, what's interesting is that the documentation conflicts with itself; it indicates JSON is expected for payloads in the general documentation, but in point of fact, only less than a handful of methods actually accept it.

I've decided to take an approach similar to [twit for node](https://github.com/ttezel/twit), where they specify a list of paths that accept JSON, and, if those are matched, they send raw JSON; otherwise, form data is provided. This will supercede #49, as that particular approach _only_ sends form-encoded data, which breaks a number of endpoints that require it.
